//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiveArt.ProductsManagement.Database.Install.Migrations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlScriptResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScriptResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiveArt.ProductsManagement.Database.Install.Migrations.SqlScriptResources", typeof(SqlScriptResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[SaveComment]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///	DROP PROCEDURE [dbo].[SaveComment]
        ///GO
        ///
        ///CREATE procedure [dbo].[SaveComment]
        ///(
        ///	@Id int,
        ///	@Author nvarchar(200),
        ///	@Message nvarchar(4000))
        ///AS
        ///BEGIN
        ///	IF (@Id = 0)
        ///		BEGIN
        ///			INSERT INTO [dbo].[Comment] (
        ///	  			[Name],
        ///      			Author,
        ///      			[Message])
        ///			VALUES (
        ///	  			@Author,
        ///      			@Message)
        ///		END
        ///	ELSE
        ///		BEGIN
        ///			UPDATE [dbo].[Comment] SET
        ///	  			Author = @Author,
        ///      			[Messag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string setup_comment_save_sp {
            get {
                return ResourceManager.GetString("setup_comment_save_sp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[SaveProduct]&apos;) AND type in (N&apos;P&apos;, N&apos;PC&apos;))
        ///	DROP PROCEDURE [dbo].[SaveProduct]
        ///GO
        ///
        ///CREATE procedure [dbo].[SaveProduct]
        ///(
        ///	@Id int,
        ///	@Name nvarchar(200),
        ///	@Description nvarchar(4000),
        ///	@ThumbnailImage nvarchar(MAX))
        ///AS
        ///BEGIN
        ///	IF (@Id = 0)
        ///		BEGIN
        ///			INSERT INTO [dbo].[Product] (
        ///	  			[Name],
        ///      			[Description],
        ///      			ThumbnailImage)
        ///			VALUES (
        ///	  			@Name,
        ///      			@Description,
        ///      			@ThumbnailImage)
        ///		END
        ///	ELSE
        ///		BE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string setup_product_save_sp {
            get {
                return ResourceManager.GetString("setup_product_save_sp", resourceCulture);
            }
        }
    }
}
